### ISSUE TITLE
Zoom in further over tiles layer

### ISSUE THREAD

**Issue by asotoopensky** [aparshin/leaflet-boundary-canvas#10]
Hi, i'm using leaflet 0.7.3 and Leaflet Boundary Canvas to render some tile layers over a map via WMTS. When I zoom in until level 20, the layer disappears and shows up Google Map.
According to Leaflet Documentation this problem is solved setting a value to **maxNativeZoom** property which prevents more server requests after level 18 but I tried to increment the **maxZoom** value  in order to zoom in to layer and didn't work. So, if I remove this plugin, the zoom works.

I want to zoom in further with out losing the tile layers, i'm ok if the layer gets some blur.

The problem is similar to this:
http://jsfiddle.net/gwacker/3kWRy/ (The layer disappears when zooming in)

The Layer options:
```
{
	tiled: true,
	format: 'image/png',
	transparent: true,
	tileSize:256,
	maxZoom: 20,
	maxNativeZoom: 18
}
```

**Comment by aparshin** [comment]
The plugin uses `L.TileLayer.Canvas` class for Leaflet v0.7.x. Unfortunately, `L.TileLayer.Canvas` doesn't support `maxNativeZoom` option. I don't think that it is reasonable to modify original code of this class in plugin or to write PR to Leaflet...

But `maxNativeZoom` option works properly in Leaflet v1.0-beta! Maybe, you can use this new version in your project...

**Comment by aparshin** [comment]
I'm closing this issue, but don't hesitate to reopen it if you have any questions or ideas!
