### ISSUE TITLE
Sometimes tiles outside of the polygon are visible.

### ISSUE THREAD

**Issue by chegga** [aparshin/leaflet-boundary-canvas#11]
You can find this bug also in your demo stuff. Please check out the screenshot.
Source: http://aparshin.github.io/leaflet-boundary-canvas/examples/canvas-boundary-providers.html

![clipboard02](https://cloud.githubusercontent.com/assets/559297/12845945/ce8822ce-cc09-11e5-9f40-7ebfea38f365.png)

This is browser independent.

**Comment by aparshin** [comment]
Confirm! Thanks! I'll fix it later today.

**Comment by aparshin** [comment]
Not Friday evening, but I've found and fixed a bug in the intersection algorithm.

Thanks again!

**Comment by chegga** [comment]
Looks good. I can't find any problems now. Thank you ver much - also if it was not friday evening ;-)
