### ISSUE TITLE
Do not download invisible tiles

### ISSUE THREAD

**Issue by fbonzon** [aparshin/leaflet-boundary-canvas#12]
Looking at the [demo](Draw boundary of a raster layer yourself) with developer tools enabled, I see that tiles falling entirely outside the given boundary are still downloaded by Leaflet (but correctly not displayed). Is this intended?

For performance, to save bandwidth and useless downloads, this plugin should prevent Leaflet from downloading tiles that will never be displayed.

**Comment by aparshin** [comment]
You are absolutely right! Thanks a lot!. Fixed.
