### ISSUE TITLE
Do not show attribution when all tiles are hidden

### ISSUE THREAD

**Issue by fbonzon** [aparshin/leaflet-boundary-canvas#13]
What do you think of the following idea? If the currently visible area of the layer is empty, i.e. made entirely of hidden tiles, do not show the attribution text for this layer.

I.e. call [removeAttribution()](https://github.com/Leaflet/Leaflet/blob/e0c17bffeeb75be044cbcac1c60155083bea914f/src/control/Control.Attribution.js#L55-L64) when, after user pan or zooms in, there are no more tiles displayed (or if the given boundary is initially entirely outside the visible viewport). Reversely if, after users pans or zooms out, at least one tile becomes visible, then call [addAttribution()](https://github.com/Leaflet/Leaflet/blob/e0c17bffeeb75be044cbcac1c60155083bea914f/src/control/Control.Attribution.js#L42-L53).

If I use this plugin to mix several layers into one (with a layer group), it would nice to see the attribution updated depending where I'm looking at.

**Comment by aparshin** [comment]
I've implemented better attribution handling, but turn it off by default because of potential performance degradation. Use new option `trackAttribution: true` to turn it on!
