### ISSUE TITLE
BoundaryCanvas not work with Leaflet 0.8

### ISSUE THREAD

**Issue by geostarters** [aparshin/leaflet-boundary-canvas#5]
In Leaflet 0.8 TileLayer.Canvas have been removed instead of GridLayer type.

**Comment by alexcroox** [comment]
Any news from them? I'm looking to use 0.8's flyTo method but also with BoundaryCanvas

**Comment by aparshin** [comment]
Well, I've temporary copied all nessesary util functions from Leaflet sources with required fixes. I hope sooner or later my PR will be merged and I remove this hack...

Anyway, now the plugin works with Leaflet 0.7.3 and with the last version from `master` branch.

@alexcroox @geostarters Can you, please, check that everything is ok?

**Comment by alexcroox** [comment]
Works OK in 0.7.3 still, can't test 0.8 just yet as [maskcanvas](https://github.com/domoritz/leaflet-maskcanvas) is also broken and my code heavily relies on it!

**Comment by aparshin** [comment]
I'm closing this issue, but don't hesitate to reopen it if you discover any bugs with 0.8 version!
