### ISSUE TITLE
Tile layer inside polygon does not show up.

### ISSUE THREAD

**Issue by migvel** [aparshin/leaflet-boundary-canvas#7]
Hello, I'm using a tile layer generated previously with gdal2tiles.

(the image from which the tile is generated is here: http://www.terracolor.net/download/tc_sanfrancisco_us_geotiff.zip )

The tile layer is loaded properly if I use the formal tileLayer, but when using boundaryCanvas
does not show up.

This is how I use it:
 tile = L.TileLayer.boundaryCanvas('terra/{z}/{x}/{y}.png', {
           minZoom: 1,
           maxZoom: 15,
           boundary: e.layer.getLatLngs(),
           tms: false
         }).addTo(map);
 tile.bringToFront();

Regards.

**Comment by aparshin** [comment]
Hello!

I don't see any obvious problems your code fragment...

You can try to localize an error in several ways:
 * Ensure that your boundary is correct. For example, you can draw it as a polygon.
 * Use other tiles (for example, OSM)
 * Remove all other layers from map (it can be z-index issue)

Or you can just publish your example and add link here...

By the way, what Leaflet version do you use?

**Comment by migvel** [comment]
The leaflet version is the 0.7.3.

If I use a tile layer from OSM boundary canvas works properly. I put the tile layer that i'm using available in a server, here the code for that url:

 tile = L.TileLayer.boundaryCanvas('http://salvoconducto.com/gis/terra/{z}/{x}/{y}.png', {
          minZoom: 1,
          maxZoom: 15,
          boundary: e.layer.getLatLngs(),
          tms: false
        }).addTo(map);

That tile layer loads properly without boundary canvas, from that, I'm guessing that the tile layer has been generated correctly.

Thanks.

**Comment by aparshin** [comment]
`tms: true` option should be used to display your tiles correctly (why `tms: false` is used in your examples?).

Looks like it is a bug with `tms` option is this plugin. I'll fix it in couple of days.

Thanks for bug report!

**Comment by aparshin** [comment]
I think I've fixed the bug.Here is an example with your tiles: http://jsbin.com/sosuqipuja/1/

**Comment by migvel** [comment]
Great, thanks!
